# Generated by Django 2.1 on 2021-02-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedGraph',
            fields=[
                ('hash_key', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('generate_method', models.CharField(choices=[('RMAT', 'RMAT')], max_length=30)),
                ('edge_count', models.IntegerField()),
                ('vertex_count', models.IntegerField()),
            ],
        ),
    ]
