# Generated by Django 2.1 on 2021-02-26 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedgraph',
            old_name='vertex_count',
            new_name='node_count',
        ),
        migrations.RemoveField(
            model_name='generatedgraph',
            name='hash_key',
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='file_hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=16, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
