# Generated by Django 2.1.1 on 2021-02-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20210226_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedgraph',
            name='generate_method',
            field=models.CharField(choices=[('SNAP_RMAT', 'SNAP_RMAT')], max_length=30),
        ),
    ]
