# Generated by Django 2.1.1 on 2021-02-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20210228_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedgraph',
            name='InDegCnt_mean',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='InDegCnt_std',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='InDegCnt_var',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='OutDegCnt_mean',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='OutDegCnt_std',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='OutDegCnt_var',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='WccSzCnt_mean',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='WccSzCnt_std',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='WccSzCnt_var',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='clust_coef',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='generatedgraph',
            name='n_triads',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='generatedgraph',
            name='edge_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='generatedgraph',
            name='node_count',
            field=models.IntegerField(default=-1),
        ),
    ]
