# Generated by Django 2.1.1 on 2021-03-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20210228_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(choices=[('SNAP_RMAT', 'SNAP_RMAT')], db_index=True, max_length=30)),
                ('duration_var', models.FloatField(default=-1)),
                ('duration_avg', models.FloatField(default=-1)),
                ('duration_std', models.FloatField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storage.GeneratedGraph')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='workloadresult',
            unique_together={('file_hash', 'experiment')},
        ),
    ]
