# Generated by Django 2.1.1 on 2021-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20210311_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedgraph',
            name='ordering',
            field=models.CharField(choices=[('default', 'default'), ('shuffle_random', 'shuffle_random')], default='default', max_length=30),
        ),
    ]
