# Generated by Django 2.1.1 on 2021-03-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20210311_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedgraph',
            name='BfsFullDiam',
            field=models.IntegerField(default=-1),
        ),
    ]
