# Generated by Django 2.1.1 on 2021-03-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_generatedgraph_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadresult',
            name='duration',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='workloadresult',
            name='exp_num',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='workloadresult',
            name='experiment',
            field=models.CharField(choices=[('SNAP_RMAT', 'SNAP_RMAT')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='workloadresult',
            name='duration_avg',
        ),
        migrations.RemoveField(
            model_name='workloadresult',
            name='duration_std',
        ),
        migrations.RemoveField(
            model_name='workloadresult',
            name='duration_var',
        ),
        migrations.AlterUniqueTogether(
            name='workloadresult',
            unique_together={('file_hash', 'experiment', 'exp_num')},
        ),
    ]
