# Generated by Django 2.1.1 on 2021-03-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_generatedgraph_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workloadresult',
            name='duration_avg',
        ),
        migrations.RemoveField(
            model_name='workloadresult',
            name='duration_std',
        ),
        migrations.RemoveField(
            model_name='workloadresult',
            name='duration_var',
        ),
        migrations.AddField(
            model_name='workloadresult',
            name='duration',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='workloadresult',
            name='exp_num',
            field=models.IntegerField(default=-1),
        ),
    ]
