# Generated by Django 2.1.1 on 2021-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20210322_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadresult',
            name='exp_num',
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
