# Generated by Django 2.1.1 on 2021-03-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20210322_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadresult',
            name='exp_num',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='workloadresult',
            name='experiment',
            field=models.CharField(choices=[('SNAP_RMAT', 'SNAP_RMAT')], max_length=30),
        ),
    ]
