# Generated by Django 2.1.1 on 2021-03-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20210322_0506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workloadresult',
            unique_together={('file_hash', 'experiment', 'exp_num')},
        ),
    ]
