# Generated by Django 2.1.1 on 2021-04-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_remove_generatedgraph_n_sinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadresult',
            name='n_sinks',
            field=models.IntegerField(default=-1),
        ),
    ]
